

import 'package:ecommerce_app/models/product_model.dart';

import '../utils/img_utils.dart';

final List<Product> productList = [
  Product(quantity: 25,

    isFavorite: false,
    name: "Product 2",
    reviews: 5000,
    description: "Product baby1 Description",
    category: "Child",
    realPrice: 389.6,
    discPrice: 90,
    image: AppImages.baby1,
  ),
  Product(quantity: 5,
    isFavorite: false,
    name: "Product 3",
    reviews: 1000,
    description: "Product baby2 Description",
    category: "Child",
    realPrice: 3540.6,
    discPrice: 1000,
    image: AppImages.baby2,
  ),
  Product(
    isFavorite: false,
    name: "Product 1",
    reviews: 5000,
    description: "Product baby3 Description",
    category: "Child",
    realPrice: 5344.6,
    discPrice: 4380,
    image: AppImages.baby3, quantity: 34,
  ),
  Product(quantity: 9,
    isFavorite: false,
    name: "Product 1",
    reviews: 1000,
    description: "Product baby4 Description",
    category: "Child",
    realPrice: 3440.6,
    discPrice: 2800,
    image: AppImages.baby4,
  ),
  Product(quantity: 10,
    isFavorite: false,
    name: "Product 1",
    reviews: 5000,
    description: "Product baby5 Description",
    category: "Child",
    realPrice: 3440.6,
    discPrice: 2780,
    image: AppImages.baby5,
  ),
  Product(quantity:28,
    isFavorite: false,
    name: "Product 1",
    reviews: 5000,
    description: "Product baby6 Description",
    category: "Child",
    realPrice: 3494.6,
    discPrice: 2580,
    image: AppImages.baby6,
  ),
//girls
  Product(
    isFavorite: false,
    name: "Product 1",
    reviews: 5000,
    description: "Product girlPic1 Description",
    category: "Woman",
    realPrice: 344.6,
    discPrice: 80,
    image: AppImages.girlPic1, quantity: 33,
  ),
  Product(
    isFavorite: false,
    name: "Product 2",
    reviews: 5000,
    description: "Product girl2 Description",
    category: "Woman",
    realPrice: 389.6,
    discPrice: 90,
    image: AppImages.girlPic2, quantity: 45,
  ),
  Product(
    isFavorite: false,
    name: "Product 3",
    reviews: 1000,
    description: "Product woman3 Description",
    category: "Woman",
    realPrice: 3540.6,
    discPrice: 1000,
    image: AppImages.girlPic3, quantity: 45,
  ),
  Product(
    isFavorite: false,
    name: "Product 1",
    reviews: 5000,
    description: "Product woman4 Description",
    category: "Woman",
    realPrice: 5344.6,
    discPrice: 4380,
    image: AppImages.girlPic4, quantity: 34,
  ),
  Product(
    isFavorite: false,
    name: "Product 1",
    reviews: 1000,
    description: "Product girl1 Description",
    category: "Woman",
    realPrice: 3440.6,
    discPrice: 2800,
    image: AppImages.girlPic5, quantity: 23,
  ),
  Product(
    isFavorite: false,
    name: "Product 1",
    reviews: 5000,
    description: "Product 1 Description",
    category: "Woman",
    realPrice: 3440.6,
    discPrice: 2780,
    image: AppImages.girlPic6, quantity: 12,
  ),

  //boys
  Product(
    isFavorite: false,
    name: "Product 1",
    reviews: 5000,
    description: "Product 1 Description",
    category: "Men",
    realPrice: 344.6,
    discPrice: 80,
    image: AppImages.boyPic1, quantity: 33,
  ),
  Product(
    isFavorite: false,
    name: "Product 2",
    reviews: 5000,
    description: "Product 1 Description",
    category: "Men",
    realPrice: 389.6,
    discPrice: 90,
    image: AppImages.boyPic2, quantity: 12,
  ),
  Product(
    isFavorite: false,
    name: "Product 3",
    reviews: 1000,
    description: "Product 1 Description",
    category: "Men",
    realPrice: 3540.6,
    discPrice: 1000,
    image: AppImages.boyPic3, quantity: 23,
  ),
  Product(
    isFavorite: false,
    name: "Product 1",
    reviews: 5000,
    description: "Product 1 Description",
    category: "Men",
    realPrice: 5344.6,
    discPrice: 4380,
    image: AppImages.boyPic4, quantity: 37,
  ),
  Product(
    isFavorite: false,
    name: "Product 1",
    reviews: 100,
    description: "Product  Description",
    category: "Men",
    realPrice: 3440.6,
    discPrice: 2800,
    image: AppImages.boyPic5, quantity: 12,
  ),
];